name: Build and Push Docker Image

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.3
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: tempconv1-389923

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          PROJECT_ID: "tempconv1-389923"
          IMAGE_NAME: "tempconv1"
          TAG: latest
        run: |
          docker build -t gcr.io/$tempconv1-389923/$tempconv1:$TAG .
          docker push gcr.io/$tempconv1-389923/$tempconv1:$TAG
