name: Deploy to Google Cloud

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
          project_id: tempconv1-389923

      - name: Configure Docker
        uses: docker/build-push-action@v2

      - name: Build and deploy
        run: |
          docker build -t flask-app .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag flask-app nagversion/9CodeReview:flask-app
          docker push nagversion/9CodeReview:flask-app
