name: Deploy to Google Cloud

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: |
            {
            "type": "service_account",
            "project_id": "tempconv1-389923",
            "private_key_id": "e4ffa96d77d2988d3381e51a6d6ebfbb39b2e731",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQDwM1akaaDApWmO\nFZhWKpaPgPE2jN8n5IybAMRTjs4Dvvi6HcQQ4km5UtEWVu5LOlKT5jOhbQtNFHZ0\nUhUQlCGljAU0vxCp3GJsXsDUFG3fvD6Kxo3n9lDFvtkYXIOOi/20Sq7vjhJTNV9z\n02OefWNJkjJ0ux6KFDAKqaqIx/jAR90vwEL8TNPf8gykAajvbO5945oaNM3b2juk\nZh6KQvhmXN3dcmDjcZfrOCk1y7VpE05jZ5pLQBwRx+yZeg9m2uFytSsvv48ks1XA\nQa8k85CGv+kIB7jR4OIY+9FH3ixWQDpzHG9/4GGYGFjJ1wGE7vf/YAB+x6njADrB\nrbi6h5CHAgMBAAECgf9qflhrjGk5AB1MYUao7TjTZteK1+oYRbwQ/MYORcIQ5xpf\nadMDqVAGWjFZNjFwKOtzpxw89ZuNEQVzjPDJ6OMCApJMUGmS5aK9aUUUwfn0uAEC\nhgVkUlB9W5/krR+mk2poBLSKgPKe8YrgT1hbbDwY4jh8iHmBvnGOSKrS+dXPaTEr\neYctL2kj+5fwiTJviYR612E5rnPunHVkSI/k+t//gMIQesZ03k0/JoZGfSviw75p\ngk/STou9lW0Ie5/h29wEvlVz26PKj2R7iTXkAofRKl9AvVOD9u15GMUuEG6TFrE/\n3/n/Il/P50X7gQAqozDhKH1n3Cxpbw2fDC6NMNECgYEA/5jBF6EIOX+yLliUS4M4\nVye8Exr2Ed2VnFThno9q9RjvyHDleGCFrU8MGzLKINIUP+HRer3ZfTThGpCMEkCB\njq3xYN6mcHCAMYbUTM04gJaMrGoGXYhKs1MxbkcNnTwPja3Pu3g5QdhbI2f4Gs4/\naV6BISCR+qugT+LFwrWMc9cCgYEA8JRddFHD16rr4vsQlL8hhmHAFzL7y4aU8ICX\nxqCHVa2Pd2L+C52p7Jsm7poYQWsofcFMUG2OZBzkMICtWe3/r4Vg4Y6xKIRiF7kG\nUrg4a604cu7zpSTXuH/QmsRKGqF5YHLSZWB+0O1Zxf4AxZ/Rtg+7FDp1yatKkadr\nOXYLMtECgYAGYGY407Cj1pa4Z0dT1vM54WjkxSBsc62+17NFRGizsqqQwphG94l+\nOGGh8BNw3CzbJyQVvtTFNeODySVlcyyIRbim5Qcb+QKJucZkIB6PvrHFv2NnQ/Yx\nIRszmBwz1wLAUxzCnY44IVCswnRDHvAgDdaE4A4kRdHbDFpIsETPwwKBgAjm5IJe\nWCnNyEaw1Y87d0kaqtnw6AJC65XunC8cV4WjE3Dud8oEPnpjz0/64bTh+zCUC3fa\nZe9sZkEpMcDnHpPnEoumFQYTx/FqxkIfUO8jDLisANX2hAjuqdBgPQG5Qd2AwipA\nJNEkRzMdT/gADul2sYxxEVSyAuNa14vbw1RRAoGAHSxpphy42Ajp8kubYoicesmO\nSE4M0Qrnm1CkeggpBuugupTJD/r5OLy3FmORmYQAdrWkSYuEANHcqqcymQXsp1Ac\ny6gx+SJOlXUFUfVoiByK5poAqzToskU2yXePm6POCISd6l8j7e6SAhXk00kWeJ1b\nxt9rniaFccaU3uEJQIc=\n-----END PRIVATE KEY-----\n",
            "client_email": "svc1-658@tempconv1-389923.iam.gserviceaccount.com",
            "client_id": "113729628629729598949",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/svc1-658%40tempconv1-389923.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
            }
