name: Deploy to Google Cloud

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          project_id: tempconv1-389923
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Configure Docker
        uses: docker/build-push-action@v2

      - name: Build and deploy
        
        run: |
             docker build -t flask-app.
             docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
             docker tag flask-app nagversion/9CodeReview:flask-app
             docker push nagversion/9CodeReview:flask-app
